### PR TITLE
Cleaned up technical debt, removed console logs, improved visualization of D3 nodes

### PR DESCRIPTION
**Pull request by guizzettic**
### **Changes Made:**

- changed dimension of nodes to be more visually striking
- Optimized timeJump action in History tab, clicking of node to dispatch action is now easier
- additional typescript support, to catch any potential errors sooner
- more descriptive psuedocode, to help onboard future developers quicker
- Cleaned up code, simplifying when necessary

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
This looks great

**Review by VNguyenCode — APPROVED** [review]
Looks good!

**Review by Theqwertypusher — APPROVED** [review]
Thanks for cleaning up. All looks good.

**Review by AlexanderLanderos — APPROVED** [review]
nice work maintaining readability throughout your code chris!

**Pull request merged**
