### PR TITLE
Optimized Visx legend key component, as well as added time jump capability to individual node click

### PR DESCRIPTION
**Pull request by guizzettic**
**Description:**
Added Legend Key component to History tab, which intuitively visualizes what the current branches of state are.
**Changes Made**
Added key timeJump feature to D3 element nodes, upon click they will invoke a timeJump to the state of that individual node
Upon click of node, the state that was selected is time traveled to and the DOM will showcase the state as well
Optimized Legend Key component using Visx, to concurrently match what is being rendered by the D3 component.
Positioned Key component, so it is available to see at all moments

**Image of the Feature**
image

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
This looks good!

**Comment by AlexanderLanderos** [comment]
looks great

**Review by Theqwertypusher — APPROVED** [review]
Love the legend key. That'll make the user experience better for sure. 

And great job implementing the timejump feature in the history. Having functional continuity is important for the UX.

**Review by AlexanderLanderos — APPROVED** [review]
Legend Key looks great and nice work on completing all of your sprints., the UI/UX is great.

**Pull request merged**
