### PR TITLE
Robby/demo app

### PR DESCRIPTION
**Pull request by RobbyTipton**
Added a demo app so users can quickly try out Reactime in a development environment.

### CODE REVIEW

**Review by khobread — APPROVED** [review]
Looks good to me!! Let's keep this folder unzipped for smoother UX for now.

**Review by joeepark — APPROVED** [review]
Looks good. Thanks for adding a demo app Robby

**Comment by codejunkie7** [comment]
Great looking application Robby.

**Review by fscgolden — APPROVED** [review]
Demo app looks good

**Review by RobbyTipton — COMMENTED** [review]
Looks good.

**Review by codejunkie7 — APPROVED** [review]
Looks amazing!

**Review by codejunkie7 — APPROVED** [review]
Solid!

**Pull request merged**
