### PR TITLE
Added new conditional check in linkFiber (setAttribute) and dispatch prop to history VISX component

### PR DESCRIPTION
**Pull request by Theqwertypusher**

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
This looks good - excited that our staging is now merging to master.

**Review by AlexanderLanderos — APPROVED** [review]
Great update to resolve the error found in codereview

**Review by guizzettic — APPROVED** [review]
Looks great, lots of new UI improvements.

**Review by SanjayLavingia — APPROVED** [review]
Looks good, great features everyone!

**Pull request merged**
