### PR TITLE
Added DOM highlighting onHover functionality for non-recoil apps to Performance Tab 

### PR DESCRIPTION
**Pull request by Theqwertypusher**
### **Description**
This feature adds an onHover functionality to the performance tab where any onMouse of a component within a barstack will highlight the corresponding DOM element. This enhances the visualization and UX because a user can quickly connect rendering times of interest to the exact component/DOM within the web page. Currently, the feature works on only non-recoil apps. 

__________________________________________________________________________________________________________________________

### **Changes I made**
- utilized storeContext to hook VISX component to state and dispatch onHover action object
- updated traversal function to extract rtid (uniquely generated ids for components building new linkfiber trees) from components within a snapshot
- created allComponentRtids object to store components and corresponding rtids for VISX barstacks to reference within onMouseMove and onMouseLeave functionality
- removed console.logs, consolidated lines, added comments, 

__________________________________________________________________________________________________________________________
### **Image of Feature**
image

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
Great addition for this feature, looking forward together to incorporate it for Recoil which I currently have in my other component.

**Review by guizzettic — APPROVED** [review]
Awesome work Jason, great way to incorporate the onHover to effectively visualize data. This will certainly improve developers production speed. Great way optimizing your performance, and adding psuedocode.

**Review by SanjayLavingia — APPROVED** [review]
LGTM!

**Review by AlexanderLanderos — APPROVED** [review]
Excellent work! really creative way to implement the onHover feature.

**Pull request merged**
