### PR TITLE
Kevin / David Filter

### PR DESCRIPTION
**Pull request by codejunkie7**
Accidental commit message on commit c5748f1, should say "Removed Console.logs and unnecessary code"

### CODE REVIEW

**Review by fscgolden — APPROVED** [review]
New filter feature looks good

**Review by khobread — APPROVED** [review]
Looks good to me! Pleasure working with you on this branch, really appreciate your communication skills in group settings David.

**Review by RobbyTipton — APPROVED** [review]
Looks good.

**Comment by codejunkie7** [comment]
Thanks guys :)

**Review by joeepark — APPROVED** [review]
Great work!

**Pull request merged**
